<?php
/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */
require ( get_template_directory() . '/includes/functions.php' );
require ( get_template_directory() . '/includes/theme-options.php' );
require ( get_template_directory() . '/includes/hooks.php' );
require ( get_template_directory() . '/includes/strap-extras.php' );
require ( get_template_directory() . '/includes/sp-shortcodes.php' );
require ( get_template_directory() . '/includes/cpt.php' );
require ( get_template_directory() . '/includes/update_notifier.php' );